# Generated by Django 3.2 on 2023-03-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='style',
            field=models.TextField(blank=True, verbose_name='Style'),
        ),
    ]
