# Generated by Django 3.2 on 2023-04-12 15:04

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.custom_user_validator], verbose_name='Имя пользователя'),
        ),
    ]
