# Generated by Django 3.2 on 2023-03-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='style',
        ),
    ]
